env:
  global:
    - secure: "cb5z3VnptesiWYQwXRQaJBdNRMQ6KI2EiNlKXYRhRI7QdNOcVeWxqK3DtfKAwPaSWs7dkLYwh9FEVdRNNNPPuzLIgnbeNvFoyLeo96+L/jXaxgYBlsJPvNJw0Rb9O9srY5VDjperr2znVe7gpAxBBHolT25t2KcpjY/x6fsRvPKQkocGDqfDFsrljZI3qZwvxkYGbIsSseu8x+KPlB6VCH9L9QRkuFUyeb+khCxV+eIkYGACvMPzIDLfbQ+GFJbEu7uiHYeB9SsZJSkQyjk6//FMGoTaZbsY5b2XaPb6hgX/yEpBnM150qtMYKgA+jAgMIiWAq8Lp4jT/8wVOkkQgnKJYwHzHpqDZR/iGdYBhC1vUldwuIm5okV+SD2gx6goUndSdTUe2xbqspIS+OOKc8iH1DGtwyinp+kJ8wc/ZF7q/6doqipjKzMpxgT0vtHCo00zdqVNlN7RLV396AEuuNp6KnaFwKYnDYIM3XsRtgsXx6RUJUYUgz83JHlSIx7hlGeHEDjYtyN7+TL62fr91VZO8VnxPa7n1+ES2qS1c1YuBU/qjajQMy1Cu/tESraDciv8vrfC5CjF57VMCJwu6QLgE00nEgzc3l9u6qEs5bOmyaqZDdRXgFN3SasPm3utzrsXIcm4xn8Bvdx2C7lxRvhqjXbjnFTR9N8//EQlXHE=" # docker user
    - secure: "g+14RO7XG4Gr1gKXsIBOtcMXFHsdcAS2egJN/lvh2xM/HkdJ7LXpuPMhr67Xv66p7JMSfDVjjSz5krp8QY8euhbpUByeoA6/rv4Z6tjNEfoIC4mM9tWrXA27dSzHp0/fVVhPR67qAJLTnEuRBNE60z+mcilqDXTB8VTd4hzjiOFo7TkylVhOJFgclGa6BaKvKkoTSsbOrH2UPATSHgZLSX3h4DiDvw2hBIggFlZ4H30nOdrRAScqJKTHl6ZcFHe4NwQ1v8AgwYv9egWCaJ5CPUnvPgfWTwUXJlvjNr1IblyiULHdwzrt+R5MnyG605Wg7/XOEJvMdiJYmlrZ/7ka3AkGHg6n3eT0lK8KLKAACOJ9hlUH5GWe68/6OobdEqxJqNnGWzBCafJgOncSVQlTWtV8BxbW3xjOjARZEdCaYe2R7p+r8bHQuB4Lx5atNYQV9/bAeXn7MXtUvn7vRXaGY6d+cfiamjCCTeLnGFYltMo7l7RqUYSJ8RRYiu6HRnCCudz0+oTHLCqnKTvxGTN6jpzXf/3XVB85qFOf0nOxle8TXBXd3vGMId+zoSrfudg21NTaTU1NFMKIUpYgvs7CAuiHZqRoMfWV4S6MPTWvMvsMh/Gjw9AxeYEsFz1WnkHuXW2pOKnYciiVzDRTR2qrCkDwJ1io89k3eoqGZ+Y8aJk=" #docker pass
    - secure: "iI02nVjNhuykQBaFx8yswHa2Ur4MuKp08rH4dpy2qtq/jdI/cq3u46E63cj0KVF/tVaQMOOgtJmBQMV66tjFxyTOeVDORouRlwwatRo1TLfUiK6Egkra4r0yLkc4HPUNTVqDAAqSojQRqoc94k+Q2CH4lR5RgsANpMcTRYO/++q0Z1k38qnqf8l6aSu/TPmMIZbHI2oEPaA/meg81aybck13xjVNZO2kJv0yltPWpWUoXhsFe31SvAvtr7CTKd0Of6DNp4OlVEwzead+rS4NpDwBoVEX//aF9dVXgcdHICNe5eeRVxuqFKbs+o4mpvYqsYrRy9f15sdrPdUutplfMMvrIHuEvAEg1c2qtOQk6MmBoYE70FN8EmMcYIUP8LZTmjLUtEA0s6Z5RWlQ9fwlCJHYeHpJnf0dk1XkgLK0WGLi4iTgcQXaJ0E4CFEwbLnB6c7ADmD1cg8sB9tVAEcZksiwCoGxJ7C+Detx0mxaqNYF2iJ51Tl8EogFlcphrG8Gs0RA39ebcoo2eqALIJ6V7cakCawuj5X1U7X8/NifzqZajo5S9v1xTn823VpT0warSG7C7hdfNBwjnWIO7o8gDun1ivIWPqSD/PhF6toiZHLpIiotALobaXYk8x2ArsqqieOW7isBMLoSEVUsCYLQ7B5LD+7GXyfVsk34BySRSQo=" # docker email
    - COMMIT=${TRAVIS_COMMIT::8}

sudo: required

language: bash

services:
  - docker

os:
- linux

git:
  depth: 150

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t homebridge homebridge/
  - docker build -t homeassistant homebassistant/

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - export REPO=gwelican/homebridge
  - docker build -t $REPO:$COMMIT homebridge
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  
  - export REPO=gwelican/homeassistant
  - docker build -t $REPO:$COMMIT homeassistant
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
